#!/usr/bin/env bash
# Script that installs Nginx server
sudo apt-get -y update
sudo apt-get -y install nginx
string="Hello World!"
echo "server {
    listen 80;
    listen [::]:80;

    location / {
	return 200 '$string';
     }
}" 
sudo service nginx start
