#!/usr/bin/env bash
# script to link sites-enabled to sites-available and restart nginx

sudo apt-get -y update
cp -a /etc/nginx/nginx.conf{,.orig}
sudo sed -i 's/sites-enabled/sites-available/' /etc/nginx/nginx.conf
sudo service nginx restart
